/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        dark: {
          "primary": "#7c3aed",
          "primary-content": "#ffffff",
          "secondary": "#3b82f6",
          "secondary-content": "#ffffff",
          "accent": "#a855f7",
          "accent-content": "#ffffff",
          "base-100": "#05060f",
          "base-200": "#0a0d1a",
          "base-300": "#12162a",
          "base-content": "#e2e8f0",
          "neutral": "#1e293b",
          "neutral-content": "#94a3b8",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
        },
        light: {
          "primary": "#7c3aed",
          "primary-content": "#ffffff",
          "secondary": "#3b82f6",
          "secondary-content": "#ffffff",
          "accent": "#a855f7",
          "accent-content": "#ffffff",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          "neutral": "#e2e8f0",
          "neutral-content": "#475569",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
        },
      },
    ],
  },
}
